import type { PhotoCrop } from './photo-url';

/**
 * The shape of what the database stores, written by hand.
 *
 * This used to be generated by Prisma from schema.prisma. Firestore has no schema to
 * generate from, which is the trade this move makes: nothing enforces these shapes at
 * write time any more, so this file is the only description of them that exists and it
 * has to be kept honest by hand.
 *
 * What that buys is everything the generation step cost — a build that could not run
 * without DIRECT_URL resolving, a migration to apply before a deploy, and a generated
 * client checked into src/. None of it was earning its place for an app whose entire
 * data access is lookups by id and three filtered lists.
 *
 * Dates are real Date objects everywhere above the data layer, exactly as they were.
 * Firestore stores them as Timestamps; db.ts converts at the boundary so nothing else
 * has to know.
 */

export type Status =
  /** Built, never reached payment. */
  | 'DRAFT'
  /** Tapped the WhatsApp button, not yet activated. */
  | 'AWAITING_CONFIRMATION'
  /** The link is live. */
  | 'ACTIVE'
  | 'EXPIRED'
  | 'REJECTED';

export type Lang = 'AR' | 'EN';

export type EventType = 'ENGAGEMENT' | 'WEDDING' | 'KATB_KETAB';

/** Prices live in src/lib/packages.ts, so changing one is not a schema question. */
export type Package =
  /** 300 EGP, link expires a while after the event. */
  | 'BASIC'
  /** 500 EGP, link never expires. */
  | 'UNLIMITED'
  /** 1000 EGP, never expires, and the couple describe a design they want. */
  | 'CUSTOM';

export type ReviewStatus =
  /** Written by a customer, not yet read by the operator. */
  | 'PENDING'
  /** Visible on the landing page. */
  | 'APPROVED'
  /** Read and rejected, kept rather than deleted. */
  | 'HIDDEN';

export type Invitation = {
  /** The Firestore document id. */
  id: string;
  /** 32 char cryptographically random. Stands in for a customer account. */
  editToken: string;
  /** Public URL, e.g. "moaaz-reem". */
  slug: string;
  /** Short and human readable, e.g. "QLT-7K4M9P". */
  requestId: string;
  status: Status;

  /** What they are paying for. Chosen on the landing page, changeable up to payment. */
  package: Package;
  /** Only the CUSTOM package collects this. */
  customRequest: string | null;

  /** Builder UI and WhatsApp message. */
  uiLang: Lang;
  /** What guests see. */
  invitationLang: Lang;

  eventType: EventType;
  name1: string;
  name2: string;
  /**
   * Null until the customer picks one.
   *
   * A draft is created on the first keystroke, long before this question is asked, and
   * it used to be born holding a date sixty days out. Stored, that is indistinguishable
   * from a chosen date: the question opened pre-filled, the guard that blocks an empty
   * answer saw a valid one, and somebody could walk to payment with a wedding booked on
   * a day they never picked.
   */
  eventDate: Date | null;
  /** "20:00", or empty until chosen — for the same reason as eventDate. */
  eventTime: string;
  venueName: string;
  venueMapUrl: string | null;
  customMessage: string | null;

  /** Which Qur'anic verse the card carries, or "none". See src/lib/verses.ts. */
  verseId: string;

  themeId: string;
  musicTrackId: string;
  /** ImageKit file id, null if no photo. */
  photoFileId: string | null;
  photoCrop: PhotoCrop | null;
  /** Generated once at activation and stored. */
  ogImageUrl: string | null;

  customerPhone: string | null;

  /**
   * What Meta needs to attribute this sale to the ad that produced it.
   *
   * Captured while the customer is still on the site and stored, because the sale is
   * not confirmed here. Payment is settled by a human on WhatsApp and the operator
   * presses Activate in the admin afterwards — a different session, a different device,
   * none of the customer's cookies. The Purchase reported at that moment can only carry
   * the original ad click if the click was written down while it was still readable.
   *
   * Null on every invitation created before this existed, and on anybody who arrived
   * without the pixel being able to run.
   */
  metaAttribution: MetaAttribution | null;

  /** Operator pastes the InstaPay reference here. */
  paymentNote: string | null;
  rejectReason: string | null;
  viewCount: number;
  activatedAt: Date | null;
  expiresAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
};

/**
 * The Meta browser signals belonging to one invitation.
 *
 * `fbc` is the valuable one: it encodes the specific ad click that brought this
 * customer here. `fbp` identifies the browser and is what matches the person when there
 * was no click to record. Address and user agent are the weaker fallbacks Meta uses
 * when neither cookie survived.
 */
export type MetaAttribution = {
  fbp: string | null;
  fbc: string | null;
  clientIp: string | null;
  userAgent: string | null;
  sourceUrl: string | null;
};

export type Review = {
  id: string;
  status: ReviewStatus;
  /** How they want to be credited, e.g. "مروة و أحمد". */
  name: string;
  city: string | null;
  body: string;
  /**
   * Set when the review came from a customer following the link on their own success
   * screen, which is the operator's evidence that it is genuine.
   */
  invitationId: string | null;
  createdAt: Date;
};

/* ---------------------------------------------------------------- photo booth */

/**
 * Where a booking is in its life.
 *
 * Only three of these take a unit off the calendar, and which three is the whole
 * design. See src/lib/photobooth/availability.ts, which is where that rule lives and
 * where it is tested.
 *
 *   REQUESTED costs nothing. Somebody filled the form in. They may never message us,
 *   and a form submission is not a reason to stop selling a Saturday night.
 *
 *   HELD costs a unit, for a while. The customer tapped through to WhatsApp, which is
 *   the first act that involves us in a conversation, and the date is theirs until the
 *   hold expires.
 *
 *   CONFIRMED costs a unit permanently. A human has seen the deposit arrive.
 *
 *   BLOCKED costs a unit and has no customer attached. It is how the operator says
 *   "the booth is at a corporate job that day" or "I am not working that week".
 */
export type BoothStatus =
  | 'REQUESTED'
  | 'HELD'
  | 'CONFIRMED'
  | 'COMPLETED'
  | 'CANCELLED'
  | 'BLOCKED';

/** Who created the booking. Bookings arrive from three places and behave differently. */
export type BoothSource = 'site' | 'admin' | 'notion';

/** How this reservation is getting on with its Notion counterpart. */
export type BoothSyncStatus = 'ok' | 'pending' | 'error';

export type BoothReservation = {
  /** The Firestore document id. */
  id: string;
  /** Short and human readable, e.g. "QLB-7K4M9P". Read aloud over WhatsApp. */
  bookingId: string;
  /**
   * The customer's key to their own status page, in an httpOnly cookie exactly like the
   * invitation editToken. There are no accounts on this side of the product either.
   */
  statusToken: string;

  status: BoothStatus;

  /**
   * A Cairo calendar day as "YYYY-MM-DD", and deliberately a string rather than a
   * Timestamp.
   *
   * A booth booking is a day, not an instant. Stored as a Timestamp, "the 14th" becomes
   * a moment in UTC, and every reader then has to agree about which timezone turns it
   * back into a day. They will not: the server runs in UTC, the operator's phone is in
   * Cairo, and for the last three hours of every Egyptian evening those two disagree
   * about the date. A booking would silently move to the day before. A string cannot
   * drift, cannot be converted by accident, and sorts correctly as text.
   */
  eventDate: string;
  /** "20:00", when the booth should be running. Not when we arrive to set it up. */
  startTime: string;
  hours: number;
  /** How many booths this booking takes. Almost always one. */
  units: number;

  packageId: string;
  price: number;
  extras: string | null;
  depositAmount: number;
  depositPaid: boolean;

  customerName: string;
  /** Egyptian local form, "01xxxxxxxxx", validated exactly as an invitation's is. */
  customerPhone: string;
  venue: string;
  area: string;
  eventType: string;
  notes: string | null;
  lang: Lang;

  source: BoothSource;

  /** When a HELD booking stops holding its unit. Null in every other status. */
  holdExpiresAt: Date | null;

  /**
   * The Meta signals belonging to this booking, captured while the customer was still
   * on the site. Same shape and same reason as an invitation's: the sale is confirmed
   * by a human on WhatsApp days later, in a session that has none of these cookies.
   */
  metaAttribution: MetaAttribution | null;

  /* Notion. Null on anything that has never been pushed. */
  notionPageId: string | null;
  /** Notion's own last_edited_time for the page, used to decide who wins a conflict. */
  notionLastEditedTime: Date | null;
  lastSyncedAt: Date | null;
  /** Hash of the synced fields. Equal hashes mean an echo of our own write. */
  syncHash: string | null;
  syncState: BoothSyncStatus;
  syncError: string | null;

  /** Why a booking was cancelled, for the operator and for the customer's status page. */
  cancelReason: string | null;

  createdAt: Date;
  updatedAt: Date;
};

/**
 * One calendar day's occupancy, and the lock that makes it true.
 *
 * This document exists so that two customers cannot take the last booth at the same
 * moment. Every write that changes a reservation's status or date runs in a Firestore
 * transaction that reads this document and writes it back, which serialises them: the
 * second transaction is retried against the first one's result rather than overwriting
 * it. Counting reservations with a query instead would be a read that is already stale
 * by the time the write lands.
 *
 * The counters are a cache of the reservations, and the reservations are the truth. The
 * reconcile job rebuilds these from the reservations nightly, because a cache that
 * nothing ever checks is a cache that is eventually wrong.
 */
export type BoothDay = {
  /** The document id is the date itself, "YYYY-MM-DD". */
  date: string;
  unitsConfirmed: number;
  unitsHeld: number;
  unitsBlocked: number;
  /** Every reservation touching this day, so the counters can be rebuilt from scratch. */
  reservationIds: string[];
  /**
   * True when a human deliberately took more bookings than there are booths. The admin
   * and Notion are both allowed to do this; the public form never is.
   */
  overbooked: boolean;
  updatedAt: Date;
};

export type BoothSettings = {
  unitCount: number;
  minNoticeDays: number;
  maxAdvanceDays: number;
  /** How long tapping through to WhatsApp holds a unit. */
  holdHours: number;
  /** JavaScript day numbers, 0 = Sunday. */
  closedWeekdays: number[];
  /** Specific days off, as "YYYY-MM-DD". */
  blackoutDates: string[];
  updatedAt: Date;
};

/** Where the Notion sync got to. One document, id "notionBooth". */
export type BoothSyncCursor = {
  /** Notion last_edited_time of the newest page already pulled in. */
  lastIncrementalCursor: string | null;
  lastIncrementalRunAt: Date | null;
  lastFullReconcileAt: Date | null;
  lastWebhookAt: Date | null;
  lastError: string | null;
  /** Held while a reconcile runs, so two do not run at once. */
  lockedUntil: Date | null;
};
