import type { PhotoCrop } from './photo-url';

/**
 * The shape of what the database stores, written by hand.
 *
 * This used to be generated by Prisma from schema.prisma. Firestore has no schema to
 * generate from, which is the trade this move makes: nothing enforces these shapes at
 * write time any more, so this file is the only description of them that exists and it
 * has to be kept honest by hand.
 *
 * What that buys is everything the generation step cost — a build that could not run
 * without DIRECT_URL resolving, a migration to apply before a deploy, and a generated
 * client checked into src/. None of it was earning its place for an app whose entire
 * data access is lookups by id and three filtered lists.
 *
 * Dates are real Date objects everywhere above the data layer, exactly as they were.
 * Firestore stores them as Timestamps; db.ts converts at the boundary so nothing else
 * has to know.
 */

export type Status =
  /** Built, never reached payment. */
  | 'DRAFT'
  /** Tapped the WhatsApp button, not yet activated. */
  | 'AWAITING_CONFIRMATION'
  /** The link is live. */
  | 'ACTIVE'
  | 'EXPIRED'
  | 'REJECTED';

export type Lang = 'AR' | 'EN';

export type EventType = 'ENGAGEMENT' | 'WEDDING' | 'KATB_KETAB';

/** Prices live in src/lib/packages.ts, so changing one is not a schema question. */
export type Package =
  /** 300 EGP, link expires a while after the event. */
  | 'BASIC'
  /** 500 EGP, link never expires. */
  | 'UNLIMITED'
  /** 1000 EGP, never expires, and the couple describe a design they want. */
  | 'CUSTOM';

export type ReviewStatus =
  /** Written by a customer, not yet read by the operator. */
  | 'PENDING'
  /** Visible on the landing page. */
  | 'APPROVED'
  /** Read and rejected, kept rather than deleted. */
  | 'HIDDEN';

export type Invitation = {
  /** The Firestore document id. */
  id: string;
  /** 32 char cryptographically random. Stands in for a customer account. */
  editToken: string;
  /** Public URL, e.g. "moaaz-reem". */
  slug: string;
  /** Short and human readable, e.g. "QLT-7K4M9P". */
  requestId: string;
  status: Status;

  /** What they are paying for. Chosen on the landing page, changeable up to payment. */
  package: Package;
  /** Only the CUSTOM package collects this. */
  customRequest: string | null;

  /** Builder UI and WhatsApp message. */
  uiLang: Lang;
  /** What guests see. */
  invitationLang: Lang;

  eventType: EventType;
  name1: string;
  name2: string;
  eventDate: Date;
  /** "20:00". */
  eventTime: string;
  venueName: string;
  venueMapUrl: string | null;
  customMessage: string | null;

  /** Which Qur'anic verse the card carries, or "none". See src/lib/verses.ts. */
  verseId: string;

  themeId: string;
  musicTrackId: string;
  /** ImageKit file id, null if no photo. */
  photoFileId: string | null;
  photoCrop: PhotoCrop | null;
  /** Generated once at activation and stored. */
  ogImageUrl: string | null;

  customerPhone: string | null;
  /** Operator pastes the InstaPay reference here. */
  paymentNote: string | null;
  rejectReason: string | null;
  viewCount: number;
  activatedAt: Date | null;
  expiresAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
};

export type Review = {
  id: string;
  status: ReviewStatus;
  /** How they want to be credited, e.g. "مروة و أحمد". */
  name: string;
  city: string | null;
  body: string;
  /**
   * Set when the review came from a customer following the link on their own success
   * screen, which is the operator's evidence that it is genuine.
   */
  invitationId: string | null;
  createdAt: Date;
};
